#!/bin/bash

# This script provides the main interface for interacting with the command line utilities used for
# configuring the behaviour of the Live Lightshow.
#
# Arguments: *see <lookup file: error messages: "lightshow: Usage:">*
#
# Return status:
# 1 on incorrect usage, otherwise $? of the given subcommand


#-Preliminaries---------------------------------#


# APP-DIRECTORY
readonly app_directory="$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd)/.."

# Imports CLI utilities.
. "$app_directory/Command Line Interface/Scripts/utilities.sh"
. "$app_directory/Lookup Files/lookup.sh"


#-Constants-------------------------------------#


# The function wrapping all constant-declarations for this script.
function declare_constants {
   # Binds the subcommand passed as first argument.
   readonly subcommand=$1
}


#-Main------------------------------------------#


declare_constants "$@"
# Shifts the given arguments to be passable to the subcommand.
shift

# Runs the script corresponding to the given subcommand, or prints and error message and returns on
# failure if the given subcommand was invalid.
case "$subcommand" in
   initialize) "$app_directory/Command Line Interface/Scripts/push_program.sh" ;;
   start) "$app_directory/Command Line Interface/start_lightshow.sh" ;;
   *)
      echo -e "$(message_for_ lightshow-usage)"; exit 1 ;;
esac
